### ISSUE TITLE
cdn? 

### ISSUE THREAD

**Issue by kimrunar** [Francessco121/msal-js-dart#35]
### Description

I'm fairly new to Flutter and Dart. But why do you use cdn-version in index.html in you examples? Is it not sufficient to use the msal-library specified in .yaml ? I'm asking because the app crashes if i don't insert the cdn-script shown in your examples index-file.

**Comment by Francessco121** [comment]
This package does not contain the implementation for MSAL, it's just a bridge between the JavaScript library and Dart. It's handled like this so that Dart projects can make use of the official MSAL.js library and all of its support and frequent patches without leaving Dart, needing to write awkward interop code, or re-implementing MSAL natively in Dart. Essentially, this package just forwards function calls to the JavaScript library and responses from it back into Dart.

Ideally, a native Dart version of MSAL would be great but it would be a large project and realistically should be done by Microsoft themselves since MSAL only works with Microsoft auth anyway.

Hope that helps.

**Comment by kimrunar** [comment]
Ok i see, thanks!
